import { z } from "zod";

/**
 * Schema for a single flashcard item generated by AI
 * Validates front (question) and back (answer) with length constraints
 */
export const FlashcardItemSchema = z.object({
  front: z
    .string({
      required_error: "Front is required",
      invalid_type_error: "Front must be a string",
    })
    .min(1, "Front must be at least 1 character")
    .max(200, "Front must not exceed 200 characters"),
  back: z
    .string({
      required_error: "Back is required",
      invalid_type_error: "Back must be a string",
    })
    .min(1, "Back must be at least 1 character")
    .max(500, "Back must not exceed 500 characters"),
});

/**
 * Schema for the complete flashcards generation response
 * Validates that the response contains 5-10 flashcards
 */
export const FlashcardsResponseSchema = z.object({
  cards: z
    .array(FlashcardItemSchema, {
      required_error: "Cards array is required",
      invalid_type_error: "Cards must be an array",
    })
    .min(5, "At least 5 flashcards must be provided")
    .max(10, "Maximum 10 flashcards allowed"),
});

/**
 * Schema for OpenRouter service configuration
 * Validates API key, model, timeout, and base URL
 */
export const OpenRouterConfigSchema = z.object({
  apiKey: z
    .string({
      required_error: "API key is required",
      invalid_type_error: "API key must be a string",
    })
    .min(20, "API key appears to be invalid (too short)"),
  defaultModel: z.string().optional().default("anthropic/claude-3-haiku"),
  timeout: z.number().int().positive().max(120000, "Timeout cannot exceed 120 seconds").optional().default(60000),
  baseUrl: z.string().url("Base URL must be a valid URL").optional().default("https://openrouter.ai/api/v1"),
});

/**
 * Type inference from schemas
 */
export type FlashcardItem = z.infer<typeof FlashcardItemSchema>;
export type FlashcardsResponse = z.infer<typeof FlashcardsResponseSchema>;
export type OpenRouterConfigInput = z.infer<typeof OpenRouterConfigSchema>;
